#cloud-config
write_files:
  - path: /etc/ssh/sshd_config.d/99-hardening.conf
    permissions: "0644"
    owner: root:root
    content: |
      PasswordAuthentication no
      KbdInteractiveAuthentication no
      ChallengeResponseAuthentication no
      PermitRootLogin prohibit-password
      PubkeyAuthentication yes

package_update: true
package_upgrade: true

runcmd:
  - sshd -t # check ssh config
  - systemctl restart ssh.service #reload ssh